version: "3.4"

services:
  web:
    image: web 
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    depends_on:
      - api
  api:
    image: api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001

