version: "3.3"

networks:
  notenet:
    driver: bridge

services:
  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 80:80
    networks:
      - notenet
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 3001:3001
    networks:
      - notenet



